# Generated by Django 2.1.5 on 2019-08-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michFit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='protein',
            field=models.CharField(max_length=10),
        ),
    ]
